# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slacktokens < Formula
  desc "Extract Slack workspace tokens and authentication cookies from the desktop app"
  homepage "https://github.com/hishamkaram/slacktokens"
  version "0.7.2"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.7.2/slacktokens_v0.7.2_darwin_amd64.tar.gz"
      sha256 "f542e1324de46bec444f07f74e54bcc8e7a2bb8420807921b541a91daaf509ed"

      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.7.2/slacktokens_v0.7.2_darwin_arm64.tar.gz"
      sha256 "3145a6ce266a69f9389cbe809a7df17e08aa366fd942becb6840086b9c277ae0"

      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.7.2/slacktokens_v0.7.2_linux_amd64.tar.gz"
      sha256 "ef65a44be82d1090723a0281adfc847ba818465666ac7d8eebd6bdf25e25c473"
      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.7.2/slacktokens_v0.7.2_linux_arm64.tar.gz"
      sha256 "0d64f4705cabaedff2cbcfb205b84ab98ed3fd6e95f5682cb493855c5516fc06"
      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
  end

  test do
    assert_match "Usage of", shell_output("#{bin}/slacktokens --help 2>&1")
    assert_predicate bin/"slacktokens-mcp", :exist?
  end
end
