# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slacktokens < Formula
  desc "Extract Slack workspace tokens and authentication cookies from the desktop app"
  homepage "https://github.com/hishamkaram/slacktokens"
  version "0.5.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.5.0/slacktokens_v0.5.0_darwin_amd64.tar.gz"
      sha256 "4475632cda3abcf95b9bd85d03770cf1d3d968b34c636e64b638f8940401e4c8"

      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.5.0/slacktokens_v0.5.0_darwin_arm64.tar.gz"
      sha256 "4dbc6c0db5df7b26744fe6f2077a1d35d1028c69a65540836df9ab202ffe5ef3"

      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.5.0/slacktokens_v0.5.0_linux_amd64.tar.gz"
      sha256 "61912d7f68b6154e43dfc320f2ae3956650b7d919688978125b9b4ed72735a25"
      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hishamkaram/slacktokens/releases/download/v0.5.0/slacktokens_v0.5.0_linux_arm64.tar.gz"
      sha256 "35403386f3269559ab1a42e1ed5e3c7db6d29e72dc0c1a0783e83a206b76ad24"
      define_method(:install) do
        bin.install "slacktokens"
        bin.install "slacktokens-mcp"
      end
    end
  end

  test do
    assert_match "Usage of", shell_output("#{bin}/slacktokens --help 2>&1")
    assert_predicate bin/"slacktokens-mcp", :exist?
  end
end
